import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import mongoose from 'mongoose'
import { randomUUID } from 'node:crypto'

const app = express(); app.use(cors()); app.use(express.json()); const port = process.env.PORT || 4000
const db = { events: [], schedules: [], negotiations: [], notifications: [], panels: [], rooms: [] }
const seed = () => {
  db.events.push({ id: 'EVT001', company: 'TCS', companyId: 'TCS', title: 'Software Engineer Interviews', eventType: 'Technical Interview', date: '2026-08-25', startTime: '10:00', endTime: '16:00', duration: 30, status: 'PENDING' })
  db.events.push({ id: 'EVT002', company: 'Microsoft', companyId: 'MICROSOFT', title: 'Product Intern Assessment', eventType: 'Online Test', date: '2026-08-25', startTime: '13:00', endTime: '16:00', duration: 60, status: 'SCHEDULED' })
  db.events.push({ id: 'EVT003', company: 'Deloitte', companyId: 'DELOITTE', title: 'Business Analyst Interviews', eventType: 'HR Interview', date: '2026-08-25', startTime: '14:00', endTime: '17:00', duration: 30, status: 'SCHEDULED' })
  db.events.push({ id: 'EVT004', company: 'Infosys', companyId: 'INFOSYS', title: 'Graduate Engineer Discussion', eventType: 'Group Discussion', date: '2026-08-26', startTime: '09:30', endTime: '12:00', duration: 30, status: 'SCHEDULED' })
  db.panels.push({ id: 'PAN-A', name: 'Technical Panel A', members: ['A. Mehta', 'S. Rao'], unavailable: [] }, { id: 'PAN-B', name: 'Technical Panel B', members: ['N. Shah', 'K. Iyer'], unavailable: [] })
  db.rooms.push({ id: 'ROOM-204', name: 'Block A - Room 204', capacity: 2, unavailable: [] }, { id: 'ROOM-201', name: 'Block A - Room 201', capacity: 2, unavailable: [] }, { id: 'ROOM-205', name: 'Block A - Room 205', capacity: 2, unavailable: [] })
  db.schedules.push({ id: 'SCH-1001', eventId: 'EVT001', studentId: 'STU101', studentName: 'Rahul Verma', company: 'TCS', panelId: 'PAN-A', panelName: 'Technical Panel A', roomId: 'ROOM-204', roomName: 'Block A - Room 204', date: '2026-08-25', startTime: '10:00', endTime: '10:30', status: 'SCHEDULED', meetingLink: '' })
  db.schedules.push({ id: 'SCH-1002', eventId: 'EVT001', studentId: 'STU102', studentName: 'Anika Rao', company: 'TCS', panelId: 'PAN-A', panelName: 'Technical Panel A', roomId: 'ROOM-204', roomName: 'Block A - Room 204', date: '2026-08-25', startTime: '10:30', endTime: '11:00', status: 'SCHEDULED', meetingLink: '' })
  db.schedules.push({ id: 'SCH-1003', eventId: 'EVT002', studentId: 'STU103', studentName: 'Meera Iyer', company: 'Microsoft', panelId: 'PAN-B', panelName: 'Technical Panel B', roomId: 'ROOM-201', roomName: 'Block A - Room 201', date: '2026-08-25', startTime: '13:00', endTime: '14:00', status: 'SCHEDULED', meetingLink: 'https://meet.example.com/microsoft-meera' })
  db.schedules.push({ id: 'SCH-1004', eventId: 'EVT003', studentId: 'STU104', studentName: 'Vikram Mehta', company: 'Deloitte', panelId: 'PAN-B', panelName: 'Technical Panel B', roomId: 'ROOM-205', roomName: 'Block A - Room 205', date: '2026-08-25', startTime: '14:00', endTime: '14:30', status: 'SCHEDULED', meetingLink: '' })
  db.schedules.push({ id: 'SCH-1005', eventId: 'EVT003', studentId: 'STU105', studentName: 'Sana Khan', company: 'Deloitte', panelId: 'PAN-A', panelName: 'Technical Panel A', roomId: 'ROOM-201', roomName: 'Block A - Room 201', date: '2026-08-25', startTime: '14:30', endTime: '15:00', status: 'SCHEDULED', meetingLink: '' })
  db.schedules.push({ id: 'SCH-1006', eventId: 'EVT004', studentId: 'STU106', studentName: 'Karan Joshi', company: 'Infosys', panelId: 'PAN-B', panelName: 'Technical Panel B', roomId: 'ROOM-204', roomName: 'Block A - Room 204', date: '2026-08-26', startTime: '09:30', endTime: '10:00', status: 'SCHEDULED', meetingLink: '' })
  db.notifications.push({ id: 'N-1', recipientId: 'STU101', recipientType: 'student', title: 'Interview scheduled', message: 'TCS Technical Interview: 10:00 AM, Block A - Room 204.', type: 'scheduled', read: false })
}
seed()
const minutes = value => { const [h, m] = value.split(':').map(Number); return h * 60 + m }
const time = value => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`
const overlaps = (a, b, c, d) => minutes(a) < minutes(d) && minutes(c) < minutes(b)
const resourceBusy = (date, start, end, key, value, ignoreId) => db.schedules.some(s => s.id !== ignoreId && s.date === date && s.status !== 'CANCELLED' && s[key] === value && overlaps(start, end, s.startTime, s.endTime))
function available(date, start, end, panelId, roomId, studentId, ignoreId) { return !resourceBusy(date, start, end, 'panelId', panelId, ignoreId) && !resourceBusy(date, start, end, 'roomId', roomId, ignoreId) && !resourceBusy(date, start, end, 'studentId', studentId, ignoreId) }
function notify(recipientId, recipientType, title, message, type) { db.notifications.push({ id: randomUUID(), recipientId, recipientType, title, message, type, read: false }) }
function scoreSlot(slot, current, schedule) { let score = 55; const reasons = []; if (slot.panelId === current.panelId) { score += 15; reasons.push('same panel') } if (slot.roomId === current.roomId) { score += 10; reasons.push('same room') } if (slot.date === current.date) { score += 10; reasons.push('same day') } const wait = Math.abs(minutes(slot.startTime) - minutes(current.startTime)); score += Math.max(0, 10 - Math.floor(wait / 30)); reasons.push('no candidate, panel, or room conflict'); if (schedule) reasons.push('no changes to other candidates'); return { ...slot, score: Math.min(score, 100), reason: reasons.map(r => `✓ ${r}`).join(' · ') } }
function findOptions(schedule) { const options = []; const preferredTimes = [11 * 60 + 30, 14 * 60, 15 * 60 + 30]; for (const cursor of preferredTimes) for (const panel of db.panels) for (const room of db.rooms) { const begin = time(cursor); const finish = time(cursor + (minutes(schedule.endTime) - minutes(schedule.startTime))); if (available(schedule.date, begin, finish, panel.id, room.id, schedule.studentId, schedule.id)) options.push(scoreSlot({ date: schedule.date, startTime: begin, endTime: finish, panelId: panel.id, roomId: room.id }, schedule, schedule)) } return options.sort((a, b) => b.score - a.score).slice(0, 3) }
function error(res, code, message, details = []) { return res.status(code).json({ error: message, details }) }
app.get('/api/health', (_, res) => res.json({ ok: true, service: 'negotiation-agent' }))
app.post('/api/events', (req, res) => { const event = { id: randomUUID(), status: 'PENDING', ...req.body }; if (!event.company || !event.eventType || !event.date) return error(res, 400, 'company, eventType, and date are required'); db.events.push(event); res.status(201).json(event) })
app.get('/api/events', (_, res) => res.json(db.events))
app.post('/api/schedules', (req, res) => { const schedule = { id: randomUUID(), status: 'SCHEDULED', ...req.body }; if (!schedule.studentId || !schedule.date || !schedule.startTime || !schedule.endTime) return error(res, 400, 'studentId, date, startTime, and endTime are required'); if (!available(schedule.date, schedule.startTime, schedule.endTime, schedule.panelId, schedule.roomId, schedule.studentId)) return error(res, 409, 'Scheduling conflict'); db.schedules.push(schedule); notify(schedule.studentId, 'student', 'Interview scheduled', `Your ${schedule.company} interview is scheduled for ${schedule.startTime} in ${schedule.roomName}.`, 'scheduled'); res.status(201).json(schedule) })
app.get('/api/schedules', (_, res) => res.json(db.schedules))
app.get('/api/schedules/:id', (req, res) => { const item = db.schedules.find(s => s.id === req.params.id); return item ? res.json(item) : error(res, 404, 'Schedule not found') })
app.put('/api/schedules/:id', (req, res) => { const item = db.schedules.find(s => s.id === req.params.id); if (!item) return error(res, 404, 'Schedule not found'); Object.assign(item, req.body); res.json(item) })
app.post('/api/schedules/:id/reschedule', (req, res) => { const item = db.schedules.find(s => s.id === req.params.id); if (!item) return error(res, 404, 'Schedule not found'); const options = findOptions(item); const negotiation = { id: `NEG-${Math.floor(1000 + Math.random() * 8999)}`, scheduleId: item.id, studentId: item.studentId, studentName: item.studentName, requestedBy: req.body.requestedBy || item.studentId, reason: req.body.reason || 'Other', description: req.body.description || '', currentSlot: { date: item.date, startTime: item.startTime, endTime: item.endTime, panelId: item.panelId, roomId: item.roomId }, suggestedSlots: options, recommendedSlot: options[0], aiReasoning: `I understood this as a ${req.body.reason || 'schedule'} conflict. I searched ${db.panels.length} panels and ${db.rooms.length} rooms, then ranked options by keeping the same panel, day, and room while avoiding other candidates.`, status: options.length ? 'WAITING_FOR_APPROVAL' : 'PENDING' }; db.negotiations.push(negotiation); res.status(201).json(negotiation) })
app.get('/api/negotiations', (_, res) => res.json(db.negotiations))
app.get('/api/negotiations/:id', (req, res) => { const item = db.negotiations.find(n => n.id === req.params.id); return item ? res.json(item) : error(res, 404, 'Negotiation not found') })
app.post('/api/negotiations/:id/analyze', (req, res) => { const item = db.negotiations.find(n => n.id === req.params.id); if (!item) return error(res, 404, 'Negotiation not found'); const schedule = db.schedules.find(s => s.id === item.scheduleId); item.suggestedSlots = findOptions(schedule); item.recommendedSlot = item.suggestedSlots[0]; item.status = 'WAITING_FOR_APPROVAL'; res.json(item) })
app.post('/api/negotiations/:id/approve', (req, res) => { const negotiation = db.negotiations.find(n => n.id === req.params.id); if (!negotiation) return error(res, 404, 'Negotiation not found'); const schedule = db.schedules.find(s => s.id === negotiation.scheduleId); const selected = negotiation.suggestedSlots.find(s => s.startTime === (req.body.startTime || negotiation.recommendedSlot.startTime)) || negotiation.recommendedSlot; if (!selected || !available(selected.date, selected.startTime, selected.endTime, selected.panelId, selected.roomId, schedule.studentId, schedule.id)) return error(res, 409, 'Selected alternative is no longer available'); const panel = db.panels.find(p => p.id === selected.panelId); const room = db.rooms.find(r => r.id === selected.roomId); Object.assign(schedule, { date: selected.date, startTime: selected.startTime, endTime: selected.endTime, panelId: selected.panelId, panelName: panel.name, roomId: selected.roomId, roomName: room.name, status: 'RESCHEDULED' }); negotiation.recommendedSlot = selected; negotiation.status = 'APPROVED'; negotiation.approvedBy = req.body.approvedBy || 'Placement Officer'; negotiation.updatedAt = new Date().toISOString(); notify(schedule.studentId, 'student', 'Interview rescheduled', `Your ${schedule.company} interview moved to ${selected.startTime}, ${room.name}.`, 'rescheduled'); notify(panel.id, 'panel', 'Panel schedule updated', `${schedule.studentName}'s ${schedule.company} interview is now at ${selected.startTime}.`, 'rescheduled'); res.json({ negotiation, schedule }) })
app.post('/api/negotiations/:id/reject', (req, res) => { const item = db.negotiations.find(n => n.id === req.params.id); if (!item) return error(res, 404, 'Negotiation not found'); item.status = 'REJECTED'; item.approvedBy = req.body.rejectedBy || 'Placement Officer'; notify(item.studentId, 'student', 'Reschedule request declined', 'Your original interview slot remains unchanged. Please contact the Placement Cell for help.', 'rejected'); res.json(item) })
app.get('/api/availability/candidate/:id', (req, res) => res.json({ resourceId: req.params.id, date: req.query.date, available: !resourceBusy(req.query.date, req.query.startTime || '00:00', req.query.endTime || '23:59', 'studentId', req.params.id) }))
app.get('/api/availability/panel/:id', (req, res) => res.json({ resourceId: req.params.id, date: req.query.date, available: !resourceBusy(req.query.date, req.query.startTime || '00:00', req.query.endTime || '23:59', 'panelId', req.params.id) }))
app.get('/api/availability/room/:id', (req, res) => res.json({ resourceId: req.params.id, date: req.query.date, available: !resourceBusy(req.query.date, req.query.startTime || '00:00', req.query.endTime || '23:59', 'roomId', req.params.id) }))
app.get('/api/notifications/:id', (req, res) => res.json(db.notifications.filter(n => n.recipientId === req.params.id)))
app.get('/api/negotiations/:id/history', (req, res) => { const n = db.negotiations.find(x => x.id === req.params.id); res.json(n ? [{ at: n.createdAt || new Date().toISOString(), actor: n.requestedBy, action: 'Request submitted', detail: n.description }, { at: n.updatedAt || new Date().toISOString(), actor: n.approvedBy || 'Negotiation Agent', action: n.status, detail: n.aiReasoning }] : []) })
const connect = process.env.MONGODB_URI ? mongoose.connect(process.env.MONGODB_URI).catch(() => console.log('MongoDB unavailable; using demo memory store')) : Promise.resolve(); connect.finally(() => app.listen(port, () => console.log(`Negotiation API running on http://localhost:${port}`)))
